apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: simplenode
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - simplenode.keptn07project-dev.keptn07-agrabner.demo.keptn.sh
  - simplenode
  http:
  - route:
    - destination:
        host: simplenode.keptn07project-dev.svc.cluster.local
